-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\testing\motor_con_ip_src_Interval_Test_Dynamic.vhd
-- Created: 2018-05-07 09:36:28
-- 
-- Generated by MATLAB 9.2 and HDL Coder 3.10
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: motor_con_ip_src_Interval_Test_Dynamic
-- Source Path: testing/motor_controller/Interval Test Dynamic
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY motor_con_ip_src_Interval_Test_Dynamic IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        up                                :   IN    std_logic_vector(23 DOWNTO 0);  -- ufix24
        u                                 :   IN    std_logic_vector(23 DOWNTO 0);  -- ufix24
        lo                                :   IN    std_logic_vector(23 DOWNTO 0);  -- ufix24
        y                                 :   OUT   std_logic
        );
END motor_con_ip_src_Interval_Test_Dynamic;


ARCHITECTURE rtl OF motor_con_ip_src_Interval_Test_Dynamic IS

  -- Signals
  SIGNAL lo_unsigned                      : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL u_unsigned                       : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL Lower_Test_relop1                : std_logic;
  SIGNAL u_1                              : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL Lower_Test_out1                  : std_logic;
  SIGNAL up_unsigned                      : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL Upper_Test_relop1                : std_logic;
  SIGNAL FixPt_Logical_Operator_out1      : std_logic;

BEGIN
  lo_unsigned <= unsigned(lo);

  u_unsigned <= unsigned(u);

  
  Lower_Test_relop1 <= '1' WHEN lo_unsigned <= u_unsigned ELSE
      '0';

  reduced_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      u_1 <= to_unsigned(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        u_1 <= u_unsigned;
      END IF;
    END IF;
  END PROCESS reduced_process;


  delayMatch1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Lower_Test_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Lower_Test_out1 <= Lower_Test_relop1;
      END IF;
    END IF;
  END PROCESS delayMatch1_process;


  up_unsigned <= unsigned(up);

  
  Upper_Test_relop1 <= '1' WHEN u_1 <= up_unsigned ELSE
      '0';

  FixPt_Logical_Operator_out1 <= Lower_Test_out1 AND Upper_Test_relop1;


  y <= FixPt_Logical_Operator_out1;

END rtl;

