-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\working_motor\motor_con_ip_src_motor_controller_pkg.vhd
-- Created: 2018-05-09 16:28:47
-- 
-- Generated by MATLAB 9.2 and HDL Coder 3.10
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE motor_con_ip_src_motor_controller_pkg IS
  TYPE vector_of_unsigned24 IS ARRAY (NATURAL RANGE <>) OF unsigned(23 DOWNTO 0);
  TYPE vector_of_unsigned4 IS ARRAY (NATURAL RANGE <>) OF unsigned(3 DOWNTO 0);
END motor_con_ip_src_motor_controller_pkg;

