ASFLAGS_ADDITIONAL = 
XILINX_ARM_CROSS_COMPILE = D:/new_Vivado_2016_2/SDK/2016.2/gnu/arm/nt/bin
TARGET_LOAD_CMD = 
TARGET_LOAD_CMD_ARGS = 
TARGET_PKG_INSTALLDIR = C:/PROGRA~3/MATLAB/SUPPOR~1/R2017a/toolbox/target/SUPPOR~1/zynq
STACK_SIZE = 64
