-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\working_motor\motor_con_ip_dut.vhd
-- Created: 2018-05-09 16:28:54
-- 
-- Generated by MATLAB 9.2 and HDL Coder 3.10
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: motor_con_ip_dut
-- Source Path: motor_con_ip/motor_con_ip_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY motor_con_ip_dut IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        Rotate_speed                      :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        Rotate_direction                  :   IN    std_logic;  -- ufix1
        ce_out                            :   OUT   std_logic;  -- ufix1
        Motor                             :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
        readback_speed_pwm                :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
        readback_direction                :   OUT   std_logic_vector(7 DOWNTO 0)  -- ufix8
        );
END motor_con_ip_dut;


ARCHITECTURE rtl OF motor_con_ip_dut IS

  -- Component Declarations
  COMPONENT motor_con_ip_src_motor_controller
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset                           :   IN    std_logic;
          Rotate_speed                    :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          Rotate_direction                :   IN    std_logic;  -- ufix1
          ce_out                          :   OUT   std_logic;  -- ufix1
          Motor                           :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
          readback_speed_pwm              :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
          readback_direction              :   OUT   std_logic_vector(7 DOWNTO 0)  -- ufix8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : motor_con_ip_src_motor_controller
    USE ENTITY work.motor_con_ip_src_motor_controller(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL Rotate_direction_sig             : std_logic;  -- ufix1
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL Motor_sig                        : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL readback_speed_pwm_sig           : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL readback_direction_sig           : std_logic_vector(7 DOWNTO 0);  -- ufix8

BEGIN
  u_motor_con_ip_src_motor_controller : motor_con_ip_src_motor_controller
    PORT MAP( clk => clk,
              clk_enable => enb,
              reset => reset,
              Rotate_speed => Rotate_speed,  -- ufix4
              Rotate_direction => Rotate_direction_sig,  -- ufix1
              ce_out => ce_out_sig,  -- ufix1
              Motor => Motor_sig,  -- ufix8
              readback_speed_pwm => readback_speed_pwm_sig,  -- ufix8
              readback_direction => readback_direction_sig  -- ufix8
              );

  Rotate_direction_sig <= Rotate_direction;

  enb <= dut_enable;

  ce_out <= ce_out_sig;

  Motor <= Motor_sig;

  readback_speed_pwm <= readback_speed_pwm_sig;

  readback_direction <= readback_direction_sig;

END rtl;

